# Generated by Django 4.0.5 on 2022-07-06 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_id', models.IntegerField(null=True)),
                ('problem_desc', models.CharField(max_length=500)),
                ('problem_defficulty', models.CharField(max_length=10)),
                ('problem_status', models.CharField(max_length=10)),
                ('problem_score', models.FloatField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='submissions',
            name='score',
        ),
        migrations.RemoveField(
            model_name='submissions',
            name='url',
        ),
        migrations.RemoveField(
            model_name='submissions',
            name='user',
        ),
        migrations.CreateModel(
            name='testcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.CharField(max_length=500)),
                ('output', models.CharField(max_length=500)),
                ('problem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='My_App.problem')),
            ],
        ),
    ]
