# Generated by Django 4.0.5 on 2022-07-13 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0004_problem_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submissions',
            old_name='problem_id',
            new_name='problem',
        ),
        migrations.RenameField(
            model_name='testcase',
            old_name='problem_id',
            new_name='problem',
        ),
        migrations.AddField(
            model_name='submissions',
            name='submitted_code',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
