# Generated by Django 4.0.5 on 2022-07-14 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('My_App', '0005_rename_problem_id_submissions_problem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissions',
            name='user',
            field=models.ForeignKey(default="1", on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
