# Generated by Django 4.0.5 on 2022-07-15 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0006_submissions_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissions',
            name='user',
        ),
    ]
